/**
 * Writes src/tokens/accents.css: one block of accent inputs per preset in
 * KT_ACCENTS, solved by accentPalette. The presets cost a page no script;
 * this keeps them in step with the function a custom colour goes through.
 *
 *     node scripts/generate-accents.js
 *
 * accent.ts has no imports, so Node runs it from source.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  accentPalette,
  accentProperties,
  KT_ACCENTS,
  KT_DEFAULT_ACCENT,
} from '../src/theme/accent.ts';

const HEADER = `/**
 * Accent presets — generated by scripts/generate-accents.js; do not edit.
 *
 * Set one on the page or on any container:
 *
 *     <html data-accent="blue">
 *
 * Each block sets the inputs colors.css reads. Violet is Kanto's default,
 * spelled out so it can reset a container inside another accent.
 */
`;

export function accentsCss() {
  const blocks = KT_ACCENTS.map(({ id, color }) => {
    const palette = id === 'violet' ? KT_DEFAULT_ACCENT : accentPalette(color);
    const lines = Object.entries(accentProperties(palette)).map(
      ([name, value]) => `  ${name}: ${value};`,
    );
    return `[data-accent='${id}'] {\n${lines.join('\n')}\n}\n`;
  });
  return `${HEADER}\n${blocks.join('\n')}`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const root = join(dirname(fileURLToPath(import.meta.url)), '..');
  writeFileSync(join(root, 'src/tokens/accents.css'), accentsCss());
}
